server:
  port: 9000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

auth:
  url:
    login: http://localhost:8080/login
    authorize: http://localhost:9000/oauth/authorize/code


