
server:
  port: 9000
spring:
  config:
    activate:
      on-profile: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      connection-timeout: 5000
      minimum-idle: 10
      maximum-pool-size: 100
  sql:
    init:
      data-locations: classpath*:schema.sql
      mode: always


auth:
  url:
    login: http://localhost:8080/login
    logout: http://localhost:8080/api/logout
    consent: http://localhost:9000/oauth/consent
    authorize: http://localhost:9000/oauth/authorize/code
  conn:
    http-client:
      schema: http
      host: localhost:8080
      connect-timeout: 3000
      read-timeout: 5000
    feign:
      url: http://localhost:8080

hibernate:
  show_sql: false
  format_sql: false
  physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

vault:
  uri: http://localhost:8200
  token: admin
  app-role:
    role-id:
    secret-id:
  secret:
    appconfig: oauth2-app/local