server:
  port: 9000
spring:
  security:
    oauth2:
      authorization:
        server:
          issuer-uri: http://localhost:8080
        provider:
          registration:
            my-client:
              client-id: my-client
              client-secret: my-secret
              redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
              authorization-grant-type: authorization_code
              scope: user


