server:
  port: 9000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
#  security:
#    oauth2:
#      authorization:
#        server:
#          issuer-uri: http://localhost:8080
#        provider:
#          registration:
#            my-client:
#              client-id: my-client
#              client-secret: my-secret
#              redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#              authorization-grant-type: authorization_code
#              scope: user


