server:
  port: 9000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      data-locations: classpath*:schema.sql
      mode: always

auth:
  url:
    login: http://localhost:8080/login
    consent: http://localhost:9000/oauth/consent
    authorize: http://localhost:9000/oauth/authorize/code


